regalia:
  signupwindow_types: []
  db:
    dsn: null
    user: null
    pass: null

email:
  service_categories:
    regalia-info-request: true
  categories:
    regalia-info-request:
      label: Regalia info request
      description: Manually-created requests for users' regalia order needs