urls:
  protocol: http

fields:
  site:
    name: Regalia plugin dev

# shared db settings
unm:
  block_unknown_netids: false
  user_source: https://secretary.unm.edu/shared_permissions/known_netids.yaml
  shared_db:
    dsn: "sqlite:${paths.base}/../../shared.sqlite"

# disable email
email:
  enabled: false

# display errors in page
errors:
  display_trace: true

# much shorter caching settings
cache:
  path: "${paths.base}/cache"
  ttl: 60
  template_ttl: 60
  content_ttl: 0

# don't cache files as long
files:
  ttl: 60

# shorter head cache time
theme:
  head_cache_ttl: 60

# show sign in
usermenu:
  guest_signin: true

# enable mock CAS for NetID signin
user_sources:
  cas:
    providers:
      netid:
        mock_cas_user: true

# really permissive umasks for ease of development
fs:
  umask_file: 0
  umask_dir: 0
