urls:
  protocol: http

fields:
  site:
    name: Regalia plugin dev

# This site should allow general sign-in, and display a prominent sign-in button
unm:
  block_unknown_netids: false
  # share a local shared DB for ous module
  user_source: https://secretary.unm.edu/shared_permissions/known_netids.yaml
  shared_db:
    dsn: "sqlite:${paths.storage}/shared.sqlite"

# show sign in
usermenu:
  guest_signin: true

# disable email
email:
  enabled: false

# display errors in page
errors:
  display_trace: true

# use UNM theme without caching head
theme:
  active_themes: [unm, unm_dev]
  head_cache_ttl: 600

# much shorter caching settings
cache:
  path: false # use system temp dir so it's not a slow bind mount in dev containers
  ttl: 60
  template_ttl: 60
  content_ttl: 0

# don't cache files as long
files:
  ttl: 600

# enable mock CAS for NetID signin
user_sources:
  cas:
    providers:
      netid:
        mock_cas_user: true

# use poor man's cron
cron:
  route_enabled: true
  poor_mans_cron: true

# really permissive umasks for filestore, so syncing works properly
fs:
  umask_file: 0
  umask_dir: 0
